import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {randomUUID} from 'node:crypto';
import {fixture} from './backend-fixture.mjs';
import {createDomain} from '../worker/domain.generated.mjs';
import {BillsBillsEngine} from '../worker/finance.mjs';
import {formatLocal,parseCsv} from '../worker/platform.mjs';

const owner={id:'11111111-1111-4111-8111-111111111111',email:'owner@example.test'};
function sample(){
 const f=fixture();f.context.setup();
 const save=(e,r)=>f.context.apiSave(e,r,'',randomUUID()).id;
 const account=save('Accounts',{bank:'Example',nickname:'Preserved account',currency:'PHP',status:'ACTIVE',reviewStatus:'VERIFIED'});
 const card=save('Cards',{accountId:account,nickname:'Preserved card',lastFour:'0123',relationship:'PRIMARY',status:'ACTIVE'});
 const transaction=save('Transactions',{accountId:account,cardId:card,transactionDate:'2026-09-01',postingDate:'2026-09-02',description:'Example item',originalDescription:'Example item',amountMinor:10000,currency:'PHP',type:'UNKNOWN',reviewStatus:'REVIEW',status:'ACTIVE'});
 const statement=save('Statements',{accountId:account,statementDate:'2026-09-03',dueDate:'2026-09-30',balanceMinor:10000,minimumMinor:1000,currency:'PHP',status:'OPEN',reconciliation:'UNVERIFIED',calendarMode:'OFF'});
 const tables={};for(const [name,s]of f.sheets){const [columns,...rows]=s.data;tables[name.slice(3)]=rows.flatMap((r,i)=>r?.some(v=>v!=='')?[{...Object.fromEntries(columns.map((c,j)=>[c,r[j]??''])),_slot:i+2}]:[]);}
 const snapshot={ownerId:owner.id,sourceSheetId:'example-workbook-id-00000000',version:1,properties:{SCHEMA_VERSION:'4',DATA_TIMEZONE:'Asia/Manila',SPREADSHEET_ID:'example-workbook-id-00000000'},tables};
 return {snapshot,account,card,transaction,statement};
}
function apply(snapshot,domain){const next=structuredClone(snapshot);for(const c of domain.changes()){next.tables[c.entity]=(next.tables[c.entity]||[]).filter(r=>r._slot!==c.slot);if(c.after)next.tables[c.entity].push({...c.after,_slot:c.slot});}next.properties=domain.properties();next.version++;return next;}
function row(d,e){return d.call('apiList',[e,{},0,'updatedAt:desc']).rows[0];}

test('database domain reads preserve all current records without writes',()=>{const {snapshot}=sample(),d=createDomain(snapshot,owner);assert.equal(d.inspect().issues.filter(i=>i.severity==='ERROR').length,0);assert.equal(d.call('apiBootstrap',[]).diagnostics.storage,'Supabase');assert.equal(row(d,'Cards').lastFour,'0123');assert.equal(row(d,'Accounts').nickname,'Preserved account');assert.deepEqual(d.changes(),[]);});
test('domain rejects mismatched owner before reading',()=>assert.throws(()=>createDomain(sample().snapshot,{id:randomUUID(),email:owner.email}),/ACCESS_DENIED/));
test('classifications and new tags save in one staged operation',()=>{const {snapshot}=sample(),d=createDomain(snapshot,owner),r=row(d,'Transactions');const result=d.call('apiSave',['TransactionReviewBatch',{items:[{id:r.id,token:r._token,type:'PURCHASE',reviewStatus:'VERIFIED',tags:'Home, Shared'}],includeSummary:true},'',randomUUID()]);assert.equal(result.rows[0].type,'PURCHASE');assert.equal(result.overview.totals.PHP.spendingMinor,10000);assert.equal(d.changes().filter(c=>c.entity==='Operations').length,1);assert.equal(d.changes().filter(c=>c.entity==='Labels').length,2);assert.equal(snapshot.tables.Transactions[0].type,'UNKNOWN');});
test('stale classifications produce no staged write',()=>{const d=createDomain(sample().snapshot,owner),r=row(d,'Transactions');assert.throws(()=>d.call('apiSave',['TransactionReviewBatch',{items:[{id:r.id,token:'f'.repeat(64),type:'PURCHASE',reviewStatus:'VERIFIED',tags:''}],includeSummary:true},'',randomUUID()]),/CONFLICT/);assert.equal(d.changes().length,0);});
test('partial and remaining full payment use the existing financial ledger',()=>{const {snapshot,statement}=sample();let d=createDomain(snapshot,owner),s=row(d,'Statements');d.call('apiSave',['StatementPayment',{statementId:statement,mode:'PARTIAL',amountMinor:4000,source:'NEW',date:'2026-09-05'},s._token,randomUUID()]);const after=apply(snapshot,d);d=createDomain(after,owner);s=row(d,'Statements');assert.equal(s.remainingMinor,6000);d.call('apiSave',['StatementPayment',{statementId:statement,mode:'FULL',amountMinor:6000,source:'NEW',date:'2026-09-06'},s._token,randomUUID()]);const result=apply(after,d);assert.equal(result.tables.BankPayments.reduce((a,r)=>a+r.amountMinor,0),10000);assert.equal(row(createDomain(result,owner),'Statements').settlement,'SETTLED');});
test('overpayment rejected without a staged payment',()=>{const d=createDomain(sample().snapshot,owner),s=row(d,'Statements');assert.throws(()=>d.call('apiSave',['StatementPayment',{statementId:s.id,mode:'PARTIAL',amountMinor:11000,source:'NEW',date:'2026-09-05'},s._token,randomUUID()]),/VALIDATION/);assert.equal(d.changes().length,0);});
test('partial snapshots append audit and operation records after historical slots',()=>{const {snapshot}=sample();snapshot.maxSlots={AuditHistory:9000,Operations:3000};snapshot.tables.AuditHistory=[];snapshot.tables.Operations=[];const d=createDomain(snapshot,owner),r=row(d,'Accounts');d.call('apiSave',['Accounts',{id:r.id,nickname:'Updated'},r._token,randomUUID()]);assert.ok(d.changes().some(c=>c.entity==='AuditHistory'&&c.slot===9001));assert.ok(d.changes().some(c=>c.entity==='Operations'&&c.slot===3001));});
test('literal descriptions and notes retain apostrophes and formula-like strings',()=>{const {snapshot}=sample(),d=createDomain(snapshot,owner),r=row(d,'Transactions');d.call('apiSave',['Transactions',{id:r.id,notes:"'=literal",description:'=SUM(1,2)'},r._token,randomUUID()]);const updated=d.changes().find(c=>c.entity==='Transactions').after;assert.equal(updated.description,'=SUM(1,2)');assert.equal(updated.notes,"'=literal");});
test('CSV parsing supports quoted cells and rejects open quotes',()=>{assert.deepEqual(parseCsv('A,B\r\n"x,y","q""z"'),[['A','B'],['x,y','q"z']]);assert.throws(()=>parseCsv('"abc'),/IMPORT/);});
test('timezone offsets preserve the intended local date',()=>{assert.equal(formatLocal('2026-09-01T17:00:00Z','Asia/Manila','yyyy-MM-dd'),'2026-09-02');assert.equal(formatLocal('2026-01-01T00:00:00Z','America/New_York','Z'),'-0500');});

const cacheSource=fs.readFileSync(new URL('../public/browse-cache.js',import.meta.url),'utf8');
function cache(){const c=vm.createContext({});vm.runInContext(cacheSource,c);let time=1000;return {cache:c.createBrowseCache(()=>time),setTime:x=>time=x};}
test('browser snapshot handles type filtering and bounded pagination without a request',()=>{const {cache:c}=cache();c.load({loadedAt:1000,issues:[],tables:{Transactions:Array.from({length:85},(_,i)=>({id:String(i).padStart(3,'0'),type:i%2?'FEE':'PURCHASE',status:'ACTIVE',transactionDate:'2026-09-01',updatedAt:String(i)}))}});assert.equal(c.list('Transactions',{type:'FEE'}).total,42);assert.equal(c.list('Transactions',{},1).rows.length,40);});
test('browser data expires and clears, with server fallback for unsupported entities',()=>{const {cache:c,setTime}=cache();c.load({loadedAt:1000,issues:[],tables:{Transactions:[]}});assert.equal(c.list('Shares',{}),null);setTime(122000);assert.equal(c.list('Transactions',{}),null);c.clear();assert.equal(c.list('Transactions'),null);});
test('confirmed classification updates patch the cached row',()=>{const {cache:c}=cache();c.load({loadedAt:1000,issues:[],tables:{Transactions:[{id:'one',type:'UNKNOWN',updatedAt:''}]}});c.patch([{id:'one',type:'FEE',updatedAt:''}],[]);assert.equal(c.list('Transactions',{type:'FEE'}).total,1);});

test('financial engine denies access before any database request',async()=>{const engine=new BillsBillsEngine({}, {OWNER_USER_ID:owner.id});const response=await engine.fetch(new Request('https://internal/finance',{method:'POST',body:JSON.stringify({session:{user:owner,complete:false},action:'apiBootstrap',args:[]})}));assert.equal(response.status,403);});

test('read cache rechecks authorization and reloads on database version changes',async()=>{
 const {snapshot}=sample(),old=globalThis.fetch;let version=1,heads=0,snapshots=0,denied=false;
 globalThis.fetch=async(url)=>{if(url.endsWith('/bb_read_version')){heads++;return denied?Response.json({message:'ACCESS_DENIED: Authenticator verification required.'},{status:403}):Response.json({ownerId:owner.id,version,day:'2026-09-14'});}if(url.endsWith('/bb_snapshot')){snapshots++;return Response.json({...snapshot,version});}throw Error('Unexpected request');};
 try{const engine=new BillsBillsEngine({}, {OWNER_USER_ID:owner.id,OWNER_EMAIL:owner.email,SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'pub'}),session={user:owner,complete:true,id:'a'.repeat(64),token:'verified-token'};
 const invoke=()=>engine.fetch(new Request('https://internal/finance',{method:'POST',body:JSON.stringify({session,action:'apiBootstrap',args:[]})}));
 const first=await (await invoke()).json();assert.equal(first.data.browseSnapshot,undefined);assert.ok(first.data.reviewBatchRevision);await invoke();assert.equal(heads,2);assert.equal(snapshots,1);version++;const changed=await (await invoke()).json();assert.equal(changed.data.databaseVersion,2);assert.equal(snapshots,2);denied=true;assert.equal((await invoke()).status,403);
 }finally{globalThis.fetch=old;}
});
test('runtime calls Supabase directly and forwards exact idempotency identity',async()=>{
 const {snapshot}=sample(),old=globalThis.fetch,calls=[];let stored=structuredClone(snapshot),receipt=null;
 globalThis.fetch=async(url,options)=>{const body=JSON.parse(options.body);calls.push({url,body,headers:options.headers});if(url.endsWith('/bb_snapshot'))return Response.json(receipt?{replayed:true,result:receipt}:stored);if(url.endsWith('/bb_commit')){assert.equal(body.p_owner,owner.id);assert.equal(body.p_session,'a'.repeat(64));assert.equal(body.p_version,1);receipt=body.p_result;return Response.json(receipt);}throw Error('Unexpected network call');};
 try{const engine=new BillsBillsEngine({}, {OWNER_USER_ID:owner.id,OWNER_EMAIL:owner.email,SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'publishable',SUPABASE_SECRET_KEY:'sb_secret_example'}),session={user:owner,complete:true,id:'a'.repeat(64),token:'verified-token'},d=createDomain(snapshot,owner),r=row(d,'Transactions'),id=randomUUID(),args=['TransactionReviewBatch',{items:[{id:r.id,token:r._token,type:'PURCHASE',reviewStatus:'VERIFIED',tags:''}],includeSummary:true},'',id],request=()=>new Request('https://internal/finance',{method:'POST',body:JSON.stringify({session,action:'apiSave',args})});assert.equal((await engine.fetch(request())).status,200);assert.equal((await engine.fetch(request())).status,200);assert.equal(calls.filter(c=>c.url.endsWith('/bb_commit')).length,1);assert.equal(calls[0].body.p_request_id,id);assert.equal(calls[0].headers.Authorization,'Bearer verified-token');assert.equal(calls[1].headers.apikey,'sb_secret_example');assert.ok(calls.every(c=>c.url.includes('supabase.co/rest/v1/rpc/')));}finally{globalThis.fetch=old;}
});
test('database mode keeps authentication and removes the required Apps Script address',async()=>{const {configuration}=await import('../worker/runtime.generated.mjs');const env={DATA_BACKEND:'supabase',APP_ORIGIN:'https://app.example.test',SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'pub',SUPABASE_SECRET_KEY:'sb_secret_test',OWNER_USER_ID:owner.id,OWNER_EMAIL:owner.email,OWNER_USERNAME:'owner',SESSION_KEY:'a'.repeat(64)};assert.doesNotThrow(()=>configuration(env));assert.throws(()=>configuration({...env,DATA_BACKEND:'sheets'}),/settings/);});
test('financial SQL exposes no client writes or security-definer routines',()=>{const sql=fs.readFileSync(new URL('../supabase/financial_storage.sql',import.meta.url),'utf8');assert.equal(/security\s+definer/i.test(sql),false);for(const table of ['bb_workspaces','bb_records','bb_mutations'])assert.ok(sql.includes('alter table public.'+table+' enable row level security'));assert.ok(sql.includes("(select auth.jwt()->>'aal')='aal2'"));assert.ok(sql.includes('for update;'));assert.ok(sql.includes('existing is distinct from b'));assert.ok(sql.includes('expires_at>now()'));});
test('new deployment uses a Durable Object and preserves legacy-mode default',()=>{const config=JSON.parse(fs.readFileSync(new URL('../wrangler.json',import.meta.url),'utf8'));assert.equal(config.durable_objects.bindings[0].class_name,'BillsBillsEngine');assert.deepEqual(config.migrations[0].new_sqlite_classes,['BillsBillsEngine']);assert.equal(config.vars?.DATA_BACKEND,undefined);});

test('failed manual backup commits only error metadata and normal reads remain database-only',async()=>{
 const {snapshot}=sample(),old=globalThis.fetch,calls=[];snapshot.properties.LAST_BACKUP='2026-09-01T00:00:00Z';snapshot.properties.LAST_BACKUP_VERSION='1';
 globalThis.fetch=async(url,options)=>{calls.push(url);if(url.endsWith('/bb_read_version'))return Response.json({ownerId:owner.id,version:snapshot.version,day:'2026-09-14'});if(url.endsWith('/bb_snapshot'))return Response.json(snapshot);if(url.endsWith('/bb_commit')){const body=JSON.parse(options.body);assert.deepEqual(body.p_changes,[]);assert.equal(body.p_properties.LAST_BACKUP,snapshot.properties.LAST_BACKUP);assert.equal(body.p_properties.LAST_BACKUP_VERSION,'1');assert.match(body.p_properties.BACKUP_ERROR,/service account/);return Response.json(body.p_result);}throw Error('Unexpected provider request');};
 try{const engine=new BillsBillsEngine({}, {OWNER_USER_ID:owner.id,OWNER_EMAIL:owner.email,SUPABASE_URL:'https://project.supabase.co',SUPABASE_PUBLISHABLE_KEY:'pub',SUPABASE_SECRET_KEY:'sb_secret_test'}),session={user:owner,complete:true,id:'a'.repeat(64),token:'verified-token'};
 const invoke=action=>engine.fetch(new Request('https://internal/finance',{method:'POST',body:JSON.stringify({session,action,args:[]})}));
 assert.equal((await invoke('apiBackup')).status,502);assert.equal((await invoke('apiBootstrap')).status,200);assert.ok(calls.every(url=>url.startsWith('https://project.supabase.co/')));
 }finally{globalThis.fetch=old;}
});


test('transaction due dates persist independently and filter by due date and statement date',()=>{
 const {snapshot,statement}=sample();let d=createDomain(snapshot,owner),r=row(d,'Transactions');
 d.call('apiSave',['Transactions',{id:r.id,dueDate:'2026-10-05',statementId:statement},r._token,randomUUID()]);
 d=createDomain(apply(snapshot,d),owner);const updated=row(d,'Transactions');assert.equal(updated.dueDate,'2026-10-05');assert.equal(updated.amountMinor,r.amountMinor);assert.equal(row(d,'Statements').dueDate,'2026-09-30');
 assert.equal(d.call('apiList',['Transactions',{dateBasis:'dueDate',from:'2026-10-01'},0,'dueDate:asc']).total,1);
 assert.equal(d.call('apiList',['Transactions',{statementDate:'2026-09-03'},0,'dueDate:asc']).total,1);
 assert.equal(d.call('apiList',['Transactions',{statementDate:'2026-09-04'},0,'dueDate:asc']).total,0);
 assert.throws(()=>d.call('apiSave',['Transactions',{id:updated.id,dueDate:'2026-02-30'},updated._token,randomUUID()]),/VALIDATION/);
});
test('installment linking preserves charge values and safely replays',()=>{
 let {snapshot,account,card}=sample(),d=createDomain(snapshot,owner);
 d.call('apiSave',['InstallmentPlans',{accountId:account,cardId:card,reference:'Example plan',startDate:'2026-09-01',monthlyMinor:10000,currency:'PHP',count:12,status:'ACTIVE'},'',randomUUID()]);
 snapshot=apply(snapshot,d);d=createDomain(snapshot,owner);const r=row(d,'Transactions'),plan=row(d,'InstallmentPlans'),id=randomUUID(),payload={planId:plan.id,items:[{id:r.id,token:r._token,number:1}]};
 const result=d.call('apiSave',['InstallmentLinks',payload,'',id]);assert.equal(result.rows[0].installmentPlanId,plan.id);assert.equal(result.rows[0].type,'INSTALLMENT');assert.equal(result.rows[0].amountMinor,r.amountMinor);assert.equal(result.rows[0].transactionDate,r.transactionDate);
 const after=apply(snapshot,d);d=createDomain(after,owner);assert.equal(d.call('apiSave',['InstallmentLinks',payload,'',id]).replayed,true);
 d=createDomain(snapshot,owner);assert.throws(()=>d.call('apiSave',['InstallmentLinks',{...payload,items:[{...payload.items[0],number:13}]},'',randomUUID()]),/length/);assert.equal(d.changes().length,0);
 assert.throws(()=>d.call('apiSave',['InstallmentLinks',{...payload,items:[{...payload.items[0],token:'f'.repeat(64)}]},'',randomUUID()]),/CONFLICT/);assert.equal(d.changes().length,0);
});

test('installment batch rejects duplicate numbers atomically',()=>{
 let {snapshot,account,card}=sample(),d=createDomain(snapshot,owner);
 d.call('apiSave',['InstallmentPlans',{accountId:account,cardId:card,reference:'Plan',startDate:'2026-09-01',monthlyMinor:10000,currency:'PHP',count:12,status:'ACTIVE'},'',randomUUID()]);snapshot=apply(snapshot,d);d=createDomain(snapshot,owner);
 d.call('apiSave',['Transactions',{accountId:account,cardId:card,transactionDate:'2026-10-01',description:'Next charge',amountMinor:10000,currency:'PHP',type:'PURCHASE',reviewStatus:'VERIFIED',status:'ACTIVE'},'',randomUUID()]);snapshot=apply(snapshot,d);d=createDomain(snapshot,owner);
 const plan=row(d,'InstallmentPlans'),rows=d.call('apiList',['Transactions',{},0,'transactionDate:asc']).rows;
 const payload={planId:plan.id,items:rows.map(r=>({id:r.id,token:r._token,number:1}))};assert.throws(()=>d.call('apiSave',['InstallmentLinks',payload,'',randomUUID()]),/distinct/);assert.equal(d.changes().length,0);
 payload.items[1].number=2;const result=d.call('apiSave',['InstallmentLinks',payload,'',randomUUID()]);assert.equal(result.rows.length,2);assert.equal(result.rows.reduce((sum,r)=>sum+r.amountMinor,0),20000);
});

test('overview includes past-due outstanding statements before future dates',()=>{
 const {snapshot}=sample();snapshot.tables.Statements[0].dueDate='2020-01-01';const d=createDomain(snapshot,owner),overview=d.call('apiBootstrap',[]).overview;
 assert.equal(overview.upcoming.length,1);assert.equal(overview.upcoming[0].dueDate,'2020-01-01');assert.equal(overview.upcoming[0].remainingMinor,10000);
});

test('CSV import retains Payment Due Date on the transaction',()=>{
 const {snapshot,card}=sample(),d=createDomain(snapshot,owner);
 const csv=['Source Hash,Source Row,Bank,Card,Last Four,Billing Cycle,Statement Date,Payment Due Date,Transaction Date,Posting Date,Description,Amount,Source Reference',['a'.repeat(64),'1','Example','Card','0123','','','2026-10-10','2026-09-10','2026-09-11','Imported charge','25.00','import-test'].join(',')].join('\n');
 const mappings={'Example | Card | 0123':{cardId:card,currency:'PHP'}},preview=d.call('apiImportPreview',[csv,mappings]);assert.equal(preview.counts.ACCEPTED,1);
 d.call('apiImportCommit',[csv,mappings,preview.token,[0],randomUUID()]);const imported=d.changes().find(c=>c.entity==='Transactions').after;assert.equal(imported.dueDate,'2026-10-10');assert.equal(imported.amountMinor,2500);
});

test('sorting applies globally before pagination with numeric values and missing dates last',()=>{
 const {snapshot}=sample(),seed=snapshot.tables.Transactions[0];snapshot.tables.Transactions=Array.from({length:85},(_,i)=>({...seed,id:'tx-'+String(i).padStart(3,'0'),_slot:i+2,amountMinor:String(85-i),dueDate:i===0?'':'2026-10-01'}));snapshot.tables.SheetBaseline=[];const d=createDomain(snapshot,owner);
 const first=d.call('apiList',['Transactions',{},0,'amountMinor:asc']),second=d.call('apiList',['Transactions',{},1,'amountMinor:asc']);assert.equal(Number(first.rows[0].amountMinor),1);assert.equal(Number(second.rows[0].amountMinor),41);
 for(const dir of ['asc','desc']){const last=d.call('apiList',['Transactions',{},2,'dueDate:'+dir]);assert.equal(last.rows.at(-1).id,'tx-000');}
});
test('card lookup labels use nicknames and nickname sorting ignores record IDs',()=>{
 const {snapshot}=sample(),card=snapshot.tables.Cards[0],tx=snapshot.tables.Transactions[0];card.nickname='Zulu';snapshot.tables.Cards.push({...card,id:'zz-card',nickname:'Alpha',_slot:3});snapshot.tables.Transactions.push({...tx,id:'second',cardId:'zz-card',_slot:3});const d=createDomain(snapshot,owner);
 const boot=d.call('apiBootstrap',[]);assert.equal(boot.lookups.Cards[0].label,'Zulu');assert.equal(boot.lookups.Accounts[0].label,'Preserved account');assert.equal(d.call('apiList',['Transactions',{},0,'cardId:asc']).rows[0].cardId,'zz-card');
});

function duplicateSample(){const data=sample(),r=data.snapshot.tables.Transactions[0];r.sourceKey='a'.repeat(64)+':1';data.snapshot.tables.Transactions.push({...r,id:'duplicate-tx',_slot:3,description:'  EXAMPLE   ITEM ',sourceKey:'b'.repeat(64)+':1'});return data;}
function duplicatePair(d){return d.call('apiList',['DuplicateReview',{},0,'updatedAt:desc']).rows[0];}
function duplicateInput(pair,mode='merge'){return {ids:pair.records.map(r=>r.id),fingerprint:pair.fingerprint,mode,survivorId:pair.records[0].id,fields:{notes:'Reviewed together'},confirmed:true};}
test('duplicate review detects normalized matches without writing and excludes different cards or currencies',()=>{const {snapshot}=duplicateSample(),d=createDomain(snapshot,owner);assert.equal(d.call('apiList',['DuplicateReview',{},0,'updatedAt:desc']).total,1);assert.equal(d.changes().length,0);snapshot.tables.Transactions[1].cardId='other-card';assert.equal(createDomain(snapshot,owner).call('apiList',['DuplicateReview',{},0,'updatedAt:desc']).total,0);});
test('keep both persists without changing charges and rechecks changed records',()=>{let {snapshot}=duplicateSample(),d=createDomain(snapshot,owner),pair=duplicatePair(d),payload=duplicateInput(pair,'keep'),id=randomUUID();d.call('apiSave',['DuplicateResolution',payload,'',id]);snapshot=apply(snapshot,d);d=createDomain(snapshot,owner);assert.equal(d.call('apiList',['DuplicateReview',{},0,'updatedAt:desc']).total,0);assert.equal(snapshot.tables.Transactions.filter(r=>r.status==='ACTIVE').length,2);assert.equal(d.call('apiSave',['DuplicateResolution',payload,'',id]).replayed,true);snapshot.tables.Transactions[0].notes='New information';assert.equal(createDomain(snapshot,owner).call('apiList',['DuplicateReview',{},0,'updatedAt:desc']).total,1);});
test('merge requires confirmation and preserves both identities and exact survivor amount',()=>{const {snapshot}=duplicateSample();let d=createDomain(snapshot,owner),pair=duplicatePair(d),payload=duplicateInput(pair),id=randomUUID();assert.throws(()=>d.call('apiSave',['DuplicateResolution',{...payload,confirmed:false},'',id]),/Confirm/);assert.equal(d.changes().length,0);d.call('apiSave',['DuplicateResolution',payload,'',id]);const after=apply(snapshot,d),rows=after.tables.Transactions;assert.equal(rows.length,2);assert.equal(rows.filter(r=>r.status==='ACTIVE').length,1);assert.equal(rows.find(r=>r.status==='ACTIVE').amountMinor,10000);assert.equal(rows.find(r=>r.status==='VOID').sourceKey,snapshot.tables.Transactions.find(r=>r.id===rows.find(t=>t.status==='VOID').id).sourceKey);assert.ok(after.tables.AuditHistory.some(r=>r.action.startsWith('DUPLICATE_MERGE')));d=createDomain(after,owner);assert.equal(d.call('apiSave',['DuplicateResolution',payload,'',id]).replayed,true);assert.equal(d.call('apiList',['DuplicateReview',{},0,'updatedAt:desc']).total,0);});
test('stale duplicates and linked financial records cannot be merged',()=>{let {snapshot}=duplicateSample(),d=createDomain(snapshot,owner),payload=duplicateInput(duplicatePair(d));snapshot.tables.Transactions[0].notes='Changed';d=createDomain(snapshot,owner);assert.throws(()=>d.call('apiSave',['DuplicateResolution',payload,'',randomUUID()]),/CONFLICT/);assert.equal(d.changes().length,0);snapshot.tables.Shares=[{id:'share',transactionId:snapshot.tables.Transactions[0].id,_slot:2}];d=createDomain(snapshot,owner);const pair=duplicatePair(d);assert.match(pair.blockers.join(' '),/share/);assert.throws(()=>d.call('apiSave',['DuplicateResolution',duplicateInput(pair),'',randomUUID()]),/Linked share/);assert.equal(d.changes().length,0);});

test('voided duplicate source rows remain protected against CSV re-import',()=>{const {snapshot,card}=duplicateSample();let d=createDomain(snapshot,owner),pair=duplicatePair(d);d.call('apiSave',['DuplicateResolution',duplicateInput(pair),'',randomUUID()]);d=createDomain(apply(snapshot,d),owner);const csv=['Source Hash,Source Row,Bank,Card,Last Four,Billing Cycle,Statement Date,Payment Due Date,Transaction Date,Posting Date,Description,Amount,Source Reference',['b'.repeat(64),'1','Example','Card','0123','','','','2026-09-01','','Example item','100.00','same source'].join(',')].join('\n');const result=d.call('apiImportPreview',[csv,{'Example | Card | 0123':{cardId:card,currency:'PHP'}}]);assert.equal(result.counts.SKIPPED,1);});

test('extended bulk edits preserve financial identity and reject changed retries',()=>{
 const {snapshot}=sample();let d=createDomain(snapshot,owner),r=row(d,'Transactions');const original={amount:r.amountMinor,account:r.accountId,card:r.cardId};
 const payload={items:[{id:r.id,token:r._token,type:r.type,reviewStatus:r.reviewStatus,tags:'Travel',category:'Shopping',dueDate:'2026-10-15',notes:'Bulk edit'}],includeSummary:true},id=randomUUID();
 const result=d.call('apiSave',['TransactionReviewBatch',payload,'',id]);assert.equal(result.rows[0].dueDate,'2026-10-15');assert.equal(result.rows[0].notes,'Bulk edit');assert.equal(result.rows[0].amountMinor,original.amount);assert.equal(result.rows[0].cardId,original.card);assert.equal(result.rows[0].accountId,original.account);
 d=createDomain(apply(snapshot,d),owner);assert.equal(d.call('apiSave',['TransactionReviewBatch',payload,'',id]).replayed,true);assert.throws(()=>d.call('apiSave',['TransactionReviewBatch',{...payload,items:[{...payload.items[0],notes:'Different'}]},'',id]),/CONFLICT/);
});
test('exact record lookup includes voided transactions and composes with type filters',()=>{
 const {snapshot}=duplicateSample();snapshot.tables.Transactions[1].status='VOID';const d=createDomain(snapshot,owner),target=snapshot.tables.Transactions[1];
 const result=d.call('apiList',['Transactions',{recordId:target.id},0,'transactionDate:desc']);assert.equal(result.total,1);assert.equal(result.rows[0].id,target.id);assert.equal(result.rows[0].status,'VOID');assert.equal(d.call('apiList',['Transactions',{recordId:'missing'},0,'transactionDate:desc']).total,0);assert.equal(d.call('apiList',['Transactions',{recordId:target.id,type:'FEE'},0,'transactionDate:desc']).total,0);
});

test('multiple types use OR and combine with category and account filters',()=>{const {snapshot}=sample(),base=snapshot.tables.Transactions[0];snapshot.tables.Transactions.push({...base,id:'fee',type:'FEE',category:'Travel',_slot:3});snapshot.tables.Transactions[0].category='Food';snapshot.tables.Transactions[0].type='PURCHASE';const d=createDomain(snapshot,owner);assert.equal(d.call('apiList',['Transactions',{type:['PURCHASE','FEE']},0,'transactionDate:desc']).total,2);assert.equal(d.call('apiList',['Transactions',{type:['PURCHASE','FEE'],category:'travel',accountId:base.accountId},0,'transactionDate:desc']).total,1);assert.equal(d.call('apiList',['Transactions',{type:'FEE'},0,'transactionDate:desc']).total,1);assert.throws(()=>d.call('apiList',['Transactions',{type:['INVALID']},0,'transactionDate:desc']),/VALIDATION/);});

for(const amount of [-4366000,4366000])test('financed principal preserves signed amount '+amount+' and counts only installment spending',()=>{
 const {snapshot}=sample();snapshot.tables.Transactions[0].amountMinor=amount;snapshot.tables.Transactions[0].sourceKey='rcbc-principal';const original=snapshot.tables.Transactions[0];snapshot.tables.Transactions.push({...original,id:'monthly-installment',_slot:3,amountMinor:1455333,type:'INSTALLMENT',sourceKey:'rcbc-monthly'});
 let d=createDomain(snapshot,owner),r=d.call('apiList',['Transactions',{recordId:original.id},0,'updatedAt:desc']).rows[0];const payload={items:[{id:r.id,token:r._token,type:'FINANCED_PRINCIPAL',reviewStatus:'VERIFIED',tags:''}],includeSummary:true},id=randomUUID();const result=d.call('apiSave',['TransactionReviewBatch',payload,'',id]);assert.equal(result.rows[0].amountMinor,amount);assert.equal(result.rows[0].sourceKey,'rcbc-principal');assert.equal(result.overview.totals.PHP.spendingMinor,1455333);assert.ok(d.changes().every(c=>!['Statements','PaymentAllocations','InstallmentPlans'].includes(c.entity)));const after=apply(snapshot,d);d=createDomain(after,owner);assert.equal(d.call('apiSave',['TransactionReviewBatch',payload,'',id]).replayed,true);assert.equal(d.call('apiList',['Transactions',{spending:'true'},0,'updatedAt:desc']).total,1);assert.equal(d.inspect().issues.filter(i=>i.severity==='ERROR').length,0);
});
test('negative installment charges still fail validation',()=>{const {snapshot}=sample();snapshot.tables.Transactions[0].amountMinor=-10000;const d=createDomain(snapshot,owner),r=row(d,'Transactions');assert.throws(()=>d.call('apiSave',['TransactionReviewBatch',{items:[{id:r.id,token:r._token,type:'INSTALLMENT',reviewStatus:'VERIFIED',tags:''}],includeSummary:true},'',randomUUID()]),/VALIDATION/);assert.equal(d.changes().length,0);});

test('chart aggregates cover twelve months and exclude principal, void and undated spending',()=>{const {snapshot}=sample(),r=snapshot.tables.Transactions[0];r.type='INSTALLMENT';r.postingDate='2026-01-10';snapshot.tables.Transactions.push({...r,id:'principal',type:'FINANCED_PRINCIPAL',amountMinor:-90000,_slot:3},{...r,id:'undated',postingDate:'',_slot:4},{...r,id:'void',status:'VOID',_slot:5});const d=createDomain(snapshot,owner),data=d.call('apiList',['OverviewCharts',{endMonth:'2026-02'},0,'']).currencies.PHP;assert.equal(data.months.length,12);assert.equal(data.months[0].month,'2025-03');assert.equal(data.months[11].month,'2026-02');assert.equal(data.months.reduce((a,r)=>a+r.amountMinor,0),10000);assert.equal(data.cards[0].amountMinor,10000);assert.equal(data.types[0].id,'INSTALLMENT');assert.equal(data.undatedCount,1);assert.throws(()=>d.call('apiList',['OverviewCharts',{endMonth:'2026-13'},0,'']),/VALIDATION/);});
test('installment principal search respects type and account and signed amounts',()=>{const {snapshot,account,card}=sample(),r=snapshot.tables.Transactions[0];r.type='FINANCED_PRINCIPAL';r.amountMinor=-90000;const d=createDomain(snapshot,owner),result=d.call('apiList',['Transactions',{type:'FINANCED_PRINCIPAL',status:'ACTIVE',accountId:account,cardId:card,currency:'PHP',q:'Example'},0,'transactionDate:desc']);assert.equal(result.total,1);assert.equal(result.rows[0].amountMinor,-90000);assert.equal(d.call('apiList',['Transactions',{type:'FINANCED_PRINCIPAL',accountId:'different'},0,'transactionDate:desc']).total,0);});

function loanSample(){let {snapshot}=sample(),d=createDomain(snapshot,owner);const result=d.call('apiSave',['Loans',{nickname:'Home',lender:'Example lender',currency:'PHP',firstDueDate:'2024-01-31',dueDay:31,termMonths:36,principalMinor:1000000,status:'ACTIVE',initialMonthlyMinor:10000,initialMonths:12},'',randomUUID()]);snapshot=apply(snapshot,d);return {snapshot,id:result.id,d:createDomain(snapshot,owner)};}
test('loan schedule clamps month ends and leaves lender-reset amounts unknown',()=>{const {d,id}=loanSample(),loan=d.call('apiList',['LoanDashboard',{loanId:id},0,'']).loans[0];assert.equal(loan.installments.length,36);assert.equal(loan.installments[1].dueDate,'2024-02-29');assert.equal(loan.installments[11].amountMinor,10000);assert.equal(loan.installments[12].amountMinor,null);});
test('historical partial loan payments replay safely and reverse allocations',()=>{let {snapshot,d,id}=loanSample();let loan=d.call('apiList',['LoanDashboard',{loanId:id},0,'']).loans[0];const payload={loanId:id,date:'2024-01-25',amountMinor:4000,reference:'history',allocations:[{number:1,amountMinor:4000}]},request=randomUUID();d.call('apiSave',['LoanPayment',payload,loan._token,request]);snapshot=apply(snapshot,d);d=createDomain(snapshot,owner);assert.equal(d.call('apiSave',['LoanPayment',payload,loan._token,request]).replayed,true);let data=d.call('apiList',['LoanDashboard',{loanId:id},0,'']);assert.equal(data.loans[0].installments[0].remainingMinor,6000);assert.equal(d.call('apiBootstrap',[]).overview.totals.PHP.spendingMinor,0);const payment=data.payments[0];d.call('apiSave',['ReverseLoanPayment',{id:payment.id},payment._token,randomUUID()]);data=createDomain(apply(snapshot,d),owner).call('apiList',['LoanDashboard',{loanId:id},0,'']);assert.equal(data.loans[0].installments[0].remainingMinor,10000);assert.equal(data.payments[0].status,'REVERSED');});
test('loan payments reject unallocated overpayments and unknown amounts',()=>{const {d,id}=loanSample(),loan=d.call('apiList',['LoanDashboard',{loanId:id},0,'']).loans[0];for(const allocations of [[{number:1,amountMinor:10001}],[{number:13,amountMinor:10001}]])assert.throws(()=>d.call('apiSave',['LoanPayment',{loanId:id,date:'2024-01-25',amountMinor:10001,allocations},loan._token,randomUUID()]),/VALIDATION/);assert.equal(d.changes().length,0);});
test('paid loan installments cannot be rewritten by schedule changes',()=>{let {snapshot,d,id}=loanSample(),loan=d.call('apiList',['LoanDashboard',{loanId:id},0,'']).loans[0];d.call('apiSave',['LoanPayment',{loanId:id,date:'2024-01-25',amountMinor:10000,allocations:[{number:1,amountMinor:10000}]},loan._token,randomUUID()]);snapshot=apply(snapshot,d);d=createDomain(snapshot,owner);const segment=d.call('apiList',['LoanDashboard',{loanId:id},0,'']).schedules[0];assert.throws(()=>d.call('apiSave',['LoanSchedules',{id:segment.id,loanId:id,startDate:segment.startDate,endDate:segment.endDate,monthlyMinor:12000,status:'ACTIVE'},segment._token,randomUUID()]),/recorded payments/);assert.equal(d.changes().length,0);});
test('multi-person shares save atomically and cannot exceed the charge',()=>{const {snapshot}=sample();snapshot.tables.Transactions[0].type='PURCHASE';snapshot.tables.People=[{id:'p1',name:'One',status:'ACTIVE',revision:1,_slot:2},{id:'p2',name:'Two',status:'ACTIVE',revision:1,_slot:3}];const d=createDomain(snapshot,owner),t=row(d,'Transactions');assert.throws(()=>d.call('apiSave',['ShareBatch',{transactionId:t.id,items:[{personId:'p1',amountMinor:6000},{personId:'p2',amountMinor:6000}]},t._token,randomUUID()]),/VALIDATION/);assert.equal(d.changes().length,0);d.call('apiSave',['ShareBatch',{transactionId:t.id,items:[{personId:'p1',amountMinor:5000},{personId:'p2',amountMinor:5000}]},t._token,randomUUID()]);assert.equal(d.changes().filter(c=>c.entity==='Shares').length,2);});

test('loan schedule changes reject overlap and invalid oversized terms',()=>{const {d,id}=loanSample();assert.throws(()=>d.call('apiSave',['LoanSchedules',{loanId:id,startDate:'2024-02-01',endDate:'2025-01-01',monthlyMinor:12000,status:'ACTIVE'},'',randomUUID()]),/overlap/);assert.throws(()=>d.call('apiSave',['Loans',{nickname:'Bad',lender:'Lender',currency:'PHP',firstDueDate:'2024-01-31',dueDay:31,termMonths:1000000000,status:'ACTIVE',initialMonthlyMinor:10000,initialMonths:12},'',randomUUID()]),/600 months/);assert.equal(d.changes().length,0);});
test('current-month card chart is independent of the selected trend year',()=>{const {snapshot}=sample(),r=snapshot.tables.Transactions[0];r.type='PURCHASE';const d=createDomain(snapshot,owner),today=d.call('apiBootstrap',[]).today;r.postingDate=today;snapshot.tables.Transactions.push({...r,id:'older',postingDate:'2020-01-01',_slot:3});const charts=createDomain(snapshot,owner).call('apiList',['OverviewCharts',{endMonth:'2020-12'},0,'']);assert.equal(charts.currencies.PHP.currentCards[0].amountMinor,10000);assert.equal(charts.currencies.PHP.months[0].amountMinor,10000);});

test('explicit loan overpayment allocation can cover two installments and rejects stale loan revisions',()=>{const {d,id}=loanSample(),loan=d.call('apiList',['LoanDashboard',{loanId:id},0,'']).loans[0],payload={loanId:id,date:'2024-02-01',amountMinor:15000,allocations:[{number:1,amountMinor:10000},{number:2,amountMinor:5000}]};assert.throws(()=>d.call('apiSave',['LoanPayment',payload,'f'.repeat(64),randomUUID()]),/CONFLICT/);d.call('apiSave',['LoanPayment',payload,loan._token,randomUUID()]);assert.equal(d.changes().filter(c=>c.entity==='LoanAllocations').length,2);});
test('share batch cannot reduce a share below an existing repayment',()=>{const {snapshot}=sample();snapshot.tables.Transactions[0].type='PURCHASE';snapshot.tables.People=[{id:'person',name:'Person',status:'ACTIVE',revision:1,_slot:2}];snapshot.tables.Shares=[{id:'share',personId:'person',transactionId:snapshot.tables.Transactions[0].id,amountMinor:10000,currency:'PHP',status:'ACTIVE',requestStatus:'NOT_REQUESTED',revision:1,_slot:2}];snapshot.tables.Repayments=[{id:'repayment',shareId:'share',date:'2026-09-01',amountMinor:6000,currency:'PHP',type:'CASH',status:'CONFIRMED',revision:1,_slot:2}];const d=createDomain(snapshot,owner),tx=row(d,'Transactions'),share=row(d,'Shares');assert.throws(()=>d.call('apiSave',['ShareBatch',{transactionId:tx.id,items:[{id:share.id,token:share._token,personId:'person',amountMinor:5000}]},tx._token,randomUUID()]),/VALIDATION/);assert.equal(d.changes().length,0);});

test('transaction editor links a bounded installment sequence and preserves amounts',()=>{
 let {snapshot,account,card}=sample(),d=createDomain(snapshot,owner);
 d.call('apiSave',['InstallmentPlans',{accountId:account,cardId:card,reference:'Plan',startDate:'2026-09-01',currency:'PHP',count:12,status:'ACTIVE'},'',randomUUID()]);
 snapshot=apply(snapshot,d);d=createDomain(snapshot,owner);const r=row(d,'Transactions'),p=row(d,'InstallmentPlans'),id=randomUUID();
 assert.throws(()=>d.call('apiSave',['Transactions',{id:r.id,type:'INSTALLMENT',installmentPlanId:p.id,installmentNumber:13},r._token,randomUUID()]),/sequence/);
 d.call('apiSave',['Transactions',{id:r.id,type:'INSTALLMENT',installmentPlanId:p.id,installmentNumber:3},r._token,id]);
 d=createDomain(apply(snapshot,d),owner);assert.equal(row(d,'Transactions').installmentNumber,3);assert.equal(row(d,'Transactions').amountMinor,r.amountMinor);
 assert.equal(d.call('apiSave',['Transactions',{id:r.id,type:'INSTALLMENT',installmentPlanId:p.id,installmentNumber:3},r._token,id]).replayed,true);
});
