import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createRequire} from 'node:module';
import {execFileSync} from 'node:child_process';
import assert from 'node:assert/strict';
const require=createRequire(path.resolve(process.argv[2]||'node_modules/playwright/package.json'));
const {chromium}=require('playwright');
const fixture=JSON.parse(execFileSync(process.execPath,['tests/browser-fixture.mjs'],{encoding:'utf8'}));

fixture.boot.lookups.Statements.forEach(s=>s.statementDate='2026-09-09');
fixture.boot.lookups.InstallmentPlans=[{id:'test-plan',label:'Example installment plan',accountId:fixture.boot.lookups.Accounts[0].id,currency:'PHP',status:'ACTIVE',count:12}];
fixture.boot.storage='supabase';fixture.boot.databaseVersion=42;
fixture.boot.diagnostics.lastBackupVersion='41';fixture.boot.diagnostics.googleConfigured=true;
const output=fs.mkdtempSync(path.join(os.tmpdir(),'cardbills-browser-'));
const browser=await chromium.launch({executablePath:process.env.BROWSER_EXECUTABLE||undefined,headless:true});
const checks=[];
try{for(const [mode,width,height]of [['desktop',1440,1000],['tablet',820,1180],['mobile',390,844]]){
 const page=await browser.newPage({viewport:{width,height}}),errors=[];
 page.on('pageerror',e=>{errors.push(e.message);console.error(e.message);});page.on('console',m=>{if(m.type()==='error')console.error(m.text());});
 async function load(file,script){
  const html=fs.readFileSync('public/'+file,'utf8').replace(/<link\b[^>]*>/g,'').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'');
  await page.setContent(html);await page.addStyleTag({content:fs.readFileSync('public/styles.css','utf8').replace(/\/fonts\/(Poppins-[A-Za-z]+\.ttf)/g,(_,name)=>'data:font/ttf;base64,'+fs.readFileSync('public/fonts/'+name).toString('base64'))});
  await page.evaluate(data=>{crypto.randomUUID=()=> '11111111-1111-4111-8111-'+String(Math.floor(Math.random()*1e12)).padStart(12,'0');window.fetch=async(url,options={})=>{let result={signedIn:false};if(url==='/api/rpc'){const req=JSON.parse(options.body);result={data:req.action==='apiBootstrap'?data.boot:req.action==='apiList'?data.lists[req.args[0]]:[]};if(req.action==='apiList'&&req.args[0]==='InstallmentOptions'){const row=req.args[1].mode==='plans'?{...data.boot.lookups.InstallmentPlans[0],reference:'Example installment plan',_token:'plan-token'}:{...data.lists.Transactions.rows[0],id:'principal-example',description:'Full purchase',type:'FINANCED_PRINCIPAL',amountMinor:-120000,_token:'principal-token'};result={data:{rows:[row],total:1,page:0}};}if(req.action==='apiList'&&req.args[1]?.recordId){const rows=data.lists[req.args[0]].rows.filter(r=>r.id===req.args[1].recordId);result={data:{rows,total:rows.length,issues:[]}};}if(req.action==='apiSave'&&req.args[0]==='LoanDetails'){if(window.failSave)return new Response(JSON.stringify({error:'Synthetic loan save failure'}),{status:500});Object.assign(data.lists.LoanList.rows.find(r=>r.id===req.args[1].id),req.args[1],{_token:'saved-loan'});result={data:{saved:true}};}if(req.action==='apiSave'&&req.args[0]==='TransactionReviewBatch'){if(window.failSave){return new Response(JSON.stringify({error:'Synthetic save failure'}),{status:500});}result={data:{rows:req.args[1].items.map(item=>Object.assign(data.lists.Transactions.rows.find(r=>r.id===item.id),item,{_token:'updated'}))}};}}return new Response(JSON.stringify(result),{headers:{'Content-Type':'application/json'}});};},fixture);
  await page.addScriptTag({content:fs.readFileSync('public/'+script,'utf8')});await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.fonts.check('14px Poppins')));
 }
 const noOverflow=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),mode+' overflow');
 const nav=async name=>{if(width<=700)await page.locator('#nav-toggle').click();await page.locator('#nav').getByRole('button',{name,exact:true}).click();};
 await load('login.html','login.js');await page.locator('#username:focus').waitFor();await page.locator('#password').fill('synthetic-password');await page.locator('#show-password').click();assert.equal(await page.locator('#password').getAttribute('type'),'text');await noOverflow();await page.screenshot({path:path.join(output,'login-'+mode+'.png'),fullPage:true});
 await load('app.html','app.js');await page.getByRole('heading',{name:'Recent transactions',exact:true}).waitFor().catch(async e=>{console.error(await page.locator('body').innerText());throw e;});await page.locator('.spending-line').waitFor();await page.getByRole('heading',{name:'Upcoming Loans',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Columns',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'Edit',exact:true}).count(),0);assert.equal(await page.locator('th[data-field="reviewStatus"],th[data-field="category"],th[data-field="tags"],th[data-field="notes"],th[data-field="assignedShares"]').count(),0);assert.equal(await page.locator('.chart-months button').count(),0);assert.equal(await page.locator('#refresh').count(),0);await page.getByRole('button',{name:'Chart settings',exact:true}).click();await page.getByRole('button',{name:'Previous year',exact:true}).waitFor();await page.keyboard.press('Escape');await page.locator('.chart-settings-button:focus').waitFor();await page.locator('.spending-line circle').last().hover();await page.locator('.spending-line circle').last().focus();await page.locator('.chart-tooltip:not([hidden])').waitFor();await page.getByRole('heading',{name:'Spending by card',exact:true}).waitFor();await noOverflow();await page.screenshot({path:path.join(output,'overview-'+mode+'.png'),fullPage:true});
 await nav('Activity');await page.getByRole('button',{name:'Import reviewed package',exact:true}).click();assert.ok(await page.locator('#dialog').evaluate(e=>e.open));await page.keyboard.press('Escape');assert.ok(!await page.locator('#dialog').evaluate(e=>e.open));
 await page.getByRole('button',{name:'Filters',exact:true}).click();await page.locator('#dialog').getByLabel('Type',{exact:true}).selectOption(['PURCHASE','FEE']);await page.getByRole('button',{name:'Apply filters',exact:true}).click();const actionButtons=page.locator('.table-actions');assert.deepEqual(await actionButtons.locator('button').allTextContents(),['Columns','Edit']);await page.getByRole('button',{name:'Edit',exact:true}).click();const first=page.locator('[data-inline-field="category"]').first();await page.getByRole('button',{name:'Columns',exact:true}).click();await page.locator('.column-settings').getByLabel('Category',{exact:true}).check();await page.keyboard.press('Escape');await first.fill('Household');await first.press('Tab');await page.getByRole('button',{name:'Columns',exact:true}).click();await page.locator('.column-settings').getByLabel('Category',{exact:true}).uncheck();await page.keyboard.press('Escape');await page.evaluate(()=>window.failSave=true);await page.locator('#save-review-changes').click();await page.getByText(/Synthetic save failure/).waitFor();assert.ok(await page.locator('[data-inline-field="category"]').count());await page.evaluate(()=>window.failSave=false);await page.locator('#save-review-changes').click();await page.getByText(/Overview updated/).waitFor();assert.equal(await page.locator('[data-transaction-row]').first().locator('[data-inline-field]').count(),0);await noOverflow();await page.screenshot({path:path.join(output,'inline-'+mode+'.png'),fullPage:true});
 assert.equal(await page.locator('td[data-field="category"]').first().isVisible(),false);await page.getByRole('button',{name:'Columns',exact:true}).click();await page.locator('.column-settings').getByLabel('Category',{exact:true}).check();assert.equal(await page.locator('td[data-field="category"]').first().isVisible(),true);await page.locator('.column-settings').getByRole('button',{name:'Reset columns'}).click();await page.keyboard.press('Escape');assert.equal(await page.locator('td[data-field="assignedShares"]').first().isVisible(),true);
 await page.getByRole('button',{name:'Assign shares',exact:true}).first().click();await page.getByRole('button',{name:'Add person',exact:true}).waitFor();await page.getByRole('button',{name:'Add person',exact:true}).click();await page.getByRole('button',{name:'Split equally',exact:true}).click();await noOverflow();await page.screenshot({path:path.join(output,'shares-'+mode+'.png'),fullPage:true});await page.keyboard.press('Escape');await page.locator('[data-sort-key="amountMinor"]').click();await page.locator('th[aria-sort="ascending"]:has([data-sort-key="amountMinor"])').waitFor();await page.locator('[data-sort-key="amountMinor"]').press('Enter');await page.locator('th[aria-sort="descending"]:has([data-sort-key="amountMinor"])').waitFor();
 await page.getByRole('button',{name:'Groceries',exact:true}).first().click();await page.getByRole('button',{name:'Link installment charges',exact:true}).click();assert.deepEqual(errors,[]);await page.getByLabel('Installment plan ID',{exact:true}).selectOption('test-plan');await page.locator('#dialog').getByRole('checkbox').first().check();await page.getByRole('spinbutton').first().fill('1');await noOverflow();await page.screenshot({path:path.join(output,'installments-'+mode+'.png'),fullPage:true});await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Edit record',exact:true}).click();await page.locator('#edit-dueDate').fill('2026-10-05');await page.locator('#edit-type').selectOption('INSTALLMENT');await page.getByRole('button',{name:'Choose financed principal',exact:true}).click();await page.getByLabel('Search installment options',{exact:true}).fill('Full');await page.locator('.installment-dropdown').getByRole('option').first().waitFor();await page.getByLabel('Search installment options',{exact:true}).press('ArrowDown');await page.locator('.installment-dropdown').getByRole('option').first().press('Enter');await page.getByText('Number of payments: 12',{exact:true}).waitFor();await page.locator('#dialog').getByRole('button',{name:'Create plan',exact:true}).click();await page.keyboard.press('Escape');assert.equal(await page.locator('#edit-dueDate').inputValue(),'2026-10-05');assert.equal(await page.locator('#edit-dueDate').getAttribute('type'),'date');await page.locator('#edit-type').selectOption('FINANCED_PRINCIPAL');await page.getByRole('button',{name:'Choose installment plan',exact:true}).click();await page.locator('.installment-dropdown').getByRole('option').first().click();assert.equal(await page.locator('#edit-installmentNumber').isVisible(),false);await page.keyboard.press('Escape');await page.keyboard.press('Escape');
 await nav('Accounts');const account=page.getByRole('button',{name:'Everyday account',exact:true});await account.click();assert.ok(await page.locator('#context-drawer').evaluate(e=>e.open));await page.screenshot({path:path.join(output,'drawer-'+mode+'.png'),fullPage:true});await page.keyboard.press('Escape');assert.ok(!await page.locator('#context-drawer').evaluate(e=>e.open));assert.ok(await account.evaluate(e=>e===document.activeElement));
 for(const [group,subsections]of Object.entries({Activity:['Review','Saved Views'],Accounts:['Statements','Bank Payments','Installments','Loans'],Collections:['Money Owed','People','Repayments'],Settings:['Workspace and Backups','Configuration']})){
  await nav(group);for(const name of subsections){await page.locator('#subnav').getByRole('button',{name,exact:true}).click();await page.locator('#title').filter({hasText:name}).waitFor();if(name==='Review'){await page.getByRole('heading',{name:'Transactions needing attention'}).waitFor();await page.getByRole('button',{name:'Set installment details',exact:true}).waitFor();assert.equal(await page.locator('.review-transactions tbody tr').count(),2);await page.getByRole('button',{name:'Choose type',exact:true}).click();assert.ok(await page.locator('.review-transactions [data-inline-field=type]').count());await page.screenshot({path:path.join(output,'review-table-'+mode+'.png'),fullPage:true});}await noOverflow();}
 }
 await nav('Activity');await page.locator('#subnav').getByRole('button',{name:'Review',exact:true}).click();await page.getByRole('button',{name:'Review merge',exact:true}).first().click();await page.getByRole('button',{name:'Continue to confirmation',exact:true}).click();await page.getByRole('button',{name:'Confirm merge',exact:true}).waitFor();await noOverflow();await page.screenshot({path:path.join(output,'duplicate-confirm-'+mode+'.png'),fullPage:true});await page.getByRole('button',{name:'Cancel',exact:true}).click();
 await nav('Collections');await page.locator('#subnav').getByRole('button',{name:'Money Owed',exact:true}).click();await page.locator('#content tbody tr').first().getByRole('button').first().click();await page.getByRole('button',{name:'Open original transaction',exact:true}).click();await page.getByRole('button',{name:'Back to Money owed',exact:true}).click();await page.getByRole('heading',{name:'Original transaction',exact:true}).waitFor();await page.keyboard.press('Escape');
 await nav('Accounts');await page.locator('#subnav').getByRole('button',{name:'Installments',exact:true}).click();await page.getByRole('button',{name:'Add installment plans',exact:true}).click();await page.getByLabel('Search financed principal transactions',{exact:true}).waitFor();await noOverflow();await page.screenshot({path:path.join(output,'principal-'+mode+'.png'),fullPage:true});await page.keyboard.press('Escape');
 await nav('Accounts');await page.locator('#subnav').getByRole('button',{name:'Loans',exact:true}).click();assert.deepEqual(await page.locator('.table-actions button').allTextContents(),['Columns','Edit']);await page.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('[data-loan-field=lender]').fill('Updated lender');await page.locator('[data-loan-field=lender]').press('Tab');await page.locator('[data-sort-key=nickname]').click();await page.locator('[data-loan-field=lender]').waitFor();assert.equal(await page.locator('[data-loan-field=lender]').inputValue(),'Updated lender');await page.evaluate(()=>window.failSave=true);await page.locator('#save-review-changes').click();await page.getByText(/Synthetic loan save failure/).waitFor();assert.equal(await page.locator('[data-loan-field=lender]').inputValue(),'Updated lender');await page.evaluate(()=>window.failSave=false);await page.locator('#save-review-changes').click();await page.locator('td[data-field=lender]').getByText('Updated lender',{exact:true}).waitFor();assert.equal(await page.locator('[data-loan-field]').count(),0);await page.screenshot({path:path.join(output,'loan-table-'+mode+'.png'),fullPage:true});await page.locator('td[data-field=nickname]').getByRole('button',{name:'Home loan',exact:true}).click();await page.getByRole('heading',{name:'Payment history',exact:true}).waitFor();await page.getByRole('button',{name:'Edit loan',exact:true}).click();await page.getByLabel('Loan nickname',{exact:true}).waitFor();await page.keyboard.press('Escape');await page.getByRole('heading',{name:'Payment history',exact:true}).waitFor();await noOverflow();assert.ok(await page.locator('#dialog').evaluate(e=>e.scrollWidth<=e.clientWidth),'loan dialog must not scroll horizontally');await page.screenshot({path:path.join(output,'loans-'+mode+'.png'),fullPage:true});await page.keyboard.press('Escape');await page.getByRole('button',{name:'Add loan',exact:true}).click();await page.getByLabel('Fixed monthly payment',{exact:true}).waitFor();await page.keyboard.press('Escape');
 await nav('Settings');await page.getByRole('button',{name:'Enable Sheets backups',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Synchronize all statements',exact:true}).count(),0);await page.screenshot({path:path.join(output,'settings-'+mode+'.png'),fullPage:true});
 assert.deepEqual(errors,[]);checks.push(mode+' auth, navigation, drawers, focus return, import dialog and all section layouts');await page.close();
}}finally{await browser.close();}
console.log(JSON.stringify({checks,output,data:'Synthetic records only'},null,2));
